---
- name: Changed sudoers so common users can reboot
  hosts: workers
  become: yes
  tasks:
   - name: sudo without password for docker group
     copy:
       content: '%docker ALL=(ALL:ALL) NOPASSWD:ALL'
       dest: /etc/sudoers.d/docker_nopasswd
       mode: 0440
