---
- name: Exchange Keys between servers
  hosts: all
  become: yes
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: Fetch the keyfile from the node to master
      tags: run
      fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{inventory_hostname}}-id_rsa.pub"
        flat: yes

    - name: Move secret key to jenkins user
      tags: run
      fetch: 
        src: "~/.ssh/id_rsa"
        dest: "/home/jenkins/.ssh/id_rsa"
        flat: yes
        
    - name: "Create user accounts"
      user:
        name: "jenkins"
    
    - name: Copy the key add to authorized_keys using Ansible module
      tags: runcd
      authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
      when: "{{ item != inventory_hostname }}"
      with_items: 
        - "{{ groups['all'] }}"       
